version: "3.9"
services:
  postgres_14:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432:5432
    volumes:
      - C:\work\volumes\postgres:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    restart: always
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 9093:9093
      - 9997:9997
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://kafka:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9997
      KAFKA_JMX_HOSTNAME: kafka

  kafka_ui:
    image: provectuslabs/kafka-ui
    container_name: kafka_ui
    ports:
      - 8090:8080
    restart: always
    environment:
      - DYNAMIC_CONFIG_ENABLED=true
#      - KAFKA_CLUSTERS_0_NAME=local
#      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
#      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
#      - KAFKA_CLUSTERS_1_NAME=dso
#      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=d5loan-kfc003lk.corp.dev.vtb:9092
#      - KAFKA_CLUSTERS_0_ZOOKEEPER=d5loan-kfc003lk.corp.dev.vtb:2181
    links:
      - kafka
      - zookeeper

  rabbit:
    image: rabbitmq:3.12-management
    ports:
      - 15672:15672
      - 5672:5672