GET http://{{host}}:{{port}}/hash
Content-Type: text/plain

my-password

###############################################################


GET http://{{host}}:{{port}}/actuator/prometheus

###############################################################


GET http://{{host}}:{{port}}/actuator/metrics

###############################################################


GET http://{{host}}:{{port}}/actuator/metrics/hash.time

###############################################################

GET http://{{host}}:{{port}}/actuator/metrics/http.server.requests

###############################################################
