spring:
  application:
    name: hash_service

server:
  port: 8080
  tomcat:
    threads:
      min-spare: 10
      max: 200
  shutdown: graceful

management:
  server:
    port: 8080
  info:
    os:
      enabled: true
    java:
      enabled: true
  metrics:
    enable:
      tomcat: true
      jvm: true
      process: true
      hikaricp: true
      system: true
      jdbc: true
      logback: true
#    distribution:
#      percentiles:
#        http.server.requests: 0.5, 0.9, 0.95, 0.99, 0.999
#      slo:
#        http.server.requests: 1ms, 10ms, 50ms
#      percentiles-histogram:
#        http.server.requests: true
  endpoint:
    loggers:
      enabled: true
    metrics:
      enabled: true
    health:
      probes:
        enabled: true # required for local spring boot tests only, in Kubernetes environment enabled by default
      show-details: always # show detailed probe results to analyze application state
      show-components: always # list all checks within each group: health, readiness, liveness
      group:
        readiness:
          include: readinessState,diskSpace,db,port # external checks to indicate Kubernetes if application is ready for traffic
        liveness:
          include: livenessState,port # internal checks to indicate Kubernetes if application requires a reboot
  export:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
#        include: '*'
        include: health,info,metrics,prometheus,loggers,features

logging:
  level:
    root: info
    com.otus.javaadvanced.controllers: debug

auth: true