services:
  hash-service:
    build:
      context: C:\Users\rudne\IdeaProjects\otus\Java-Advanced\hash-service\
      dockerfile: Dockerfile
    hostname: hash-service
    container_name: hash-service
    restart: "no"
    ports:
      - 8080:8080
    networks:
      - otus
    environment:
      AUTH: false

  prometheus:
    image: prom/prometheus
    depends_on:
      - hash-service
    container_name: prometheus
    ports:
      - 9090:9090
    networks:
      - otus
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always
    hostname: prometheus

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    networks:
      - otus
    restart: always

networks:
  otus:
    driver: bridge